apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - service.yaml
  - servicemonitor.yaml
  - canary-service.yaml
  - hpa.yaml
  - rollout.yaml
  - analysis-template.yaml

images:
  - name: satyamgrao007/lovable-api-gateway
    newTag: "1"