apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: workspace-service
  namespace: monitoring
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: workspace-service

  namespaceSelector:
    matchNames:
      - lovable-core

  endpoints:
    - port: http
      path: /actuator/prometheus
      interval: 15s