apiVersion: v1
kind: ConfigMap
metadata:
  name: lovable-shared-config
  namespace: lovable-core

data:
  PREVIEW_DOMAIN: ""
  PREVIEW_NAMESPACE: ".previews.127.0.0.1.nip.io"
  PROXY_PORT: "80"
  APP_FRONTEND_URL: "https://127.0.0.1 lovable.localdev.me"





# previews.snapcart.dev