apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: lovable-core

resources:
  - deployment.yaml
  - service.yaml
  - servicemonitor.yaml

images:
  - name: satyamgrao007/lovable-account-service
    newTag: "9"